// Monte Carlo option pricer: implementation and validation.
// Every number below is read from results.json, generated by build_assets.py.
// Build from the repository root:
//   python3 report/build_assets.py
//   typst compile --root . report/report.typ report/option_pricer_report.pdf

#let R = json("results.json")

// Public repository of the code. Set it to the URL string (e.g. "https://github.com/<user>/option-pricer")
// once the repository exists; while it is `none`, the note says the code is available on request.
#let repo = "https://github.com/FedeDiCandia/monte-carlo-option-pricer"

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

#set document(title: "Monte Carlo pricing of European and path-dependent options", author: "Federico Di Candia")
#set page(paper: "a4", margin: (x: 2.9cm, top: 3cm, bottom: 3cm), numbering: "1")
#set text(font: "Libertinus Serif", size: 11pt, lang: "en")
#set par(justify: true, leading: 0.62em, spacing: 0.62em, first-line-indent: 1.2em)

#set heading(numbering: "1.1")
#show heading: set text(weight: "bold")
#show heading.where(level: 1): set text(size: 13pt)
#show heading.where(level: 1): set block(above: 1.8em, below: 1em)
#show heading.where(level: 2): set text(size: 11pt)
#show heading.where(level: 2): set block(above: 1.4em, below: 0.8em)

#set math.equation(numbering: none)
#show math.equation.where(block: true): set block(above: 0.9em, below: 0.9em)

#show raw: set text(font: "DejaVu Sans Mono", size: 8.6pt)
#show raw.where(block: true): it => block(
  fill: luma(246), stroke: (left: 1.2pt + luma(205)), inset: (x: 10pt, y: 8pt), width: 100%, it,
)

#set list(indent: 0.6em, body-indent: 0.5em)

// Captions as in the author's previous note: bold label, justified text, slightly smaller
#show figure.caption: it => {
  set text(size: 10pt)
  set par(first-line-indent: 0em, justify: true)
  align(left)[#strong[#it.supplement #context it.counter.display(it.numbering):] #it.body]
}
#show figure.where(kind: table): set figure.caption(position: top)
#set figure(gap: 0.9em)
#show figure: set block(above: 1.4em, below: 1.4em)
#show figure.where(kind: image): set figure(placement: auto)

// Tables with horizontal rules only
#set table(stroke: none, inset: (x: 5pt, y: 3.2pt))
#show table: set text(size: 9.5pt)
#let toprule = table.hline(stroke: 0.8pt)
#let midrule = table.hline(stroke: 0.4pt)
#let bottomrule = table.hline(stroke: 0.8pt)

// ---------------------------------------------------------------------------
// Title and abstract
// ---------------------------------------------------------------------------

#v(1.2cm)
#align(center)[
  #text(size: 17pt)[Monte Carlo pricing of European and path-dependent options:\ implementation and validation against closed-form results]
  #v(1em)
  #text(size: 12pt)[Federico Di Candia]
  #v(0.6em)
  16 September 2026
]
#v(1.1cm)

#align(center, text(weight: "bold")[Abstract])
#v(0.2em)
#pad(x: 1.3cm)[
  #set text(size: 10pt)
  #set par(first-line-indent: (amount: 1.2em, all: true))
  This note describes a Monte Carlo option pricer written in Python and the tests used to check it. The underlying follows a geometric Brownian motion under the risk-neutral measure, simulated exactly on a time grid. The pricer covers European calls and puts, arithmetic Asian options and discretely monitored barrier options, and estimates delta, gamma and vega by central finite differences with common random numbers. Every estimate carries a standard error, and every check is statistical. European prices agree with the Black–Scholes formula in twelve scenarios, with a largest deviation of #R.scenarios.max_abs_z standard errors; the one value outside its 95% interval is shown to be chance by repeating the test. Asian and barrier prices agree with independent closed-form references, and finite-difference Greeks with their analytic values. No novelty is claimed for the methods, which are textbook material; the contribution is a tested and reproducible implementation.
]

// ---------------------------------------------------------------------------

= Introduction

A Monte Carlo pricer computes the price of a derivative as the discounted expectation of its payoff under the risk-neutral measure, approximated by an average over simulated scenarios. The approach needs nothing more than the payoff evaluated on a simulated path, so a single engine prices European, Asian and barrier options alike. It has two weaknesses. The statistical error decreases only as $1\/sqrt(N)$ in the number of paths $N$, and an estimate can be precise without being correct: an error in the model or in a payoff produces a wrong number with a small standard error.

This note describes such a pricer and, above all, how it was tested. The strategy is to validate the engine where exact answers are known before relying on it where they are not. Every Monte Carlo number is reported with its standard error SE, and agreement with a reference value $V$ is measured by the z-score
$ z = (hat(V) - V) / "SE", $
which is approximately standard normal when the implementation is correct: $|z| < 1.96$ in about 95% of independent tests, while values far beyond 3 point to an error.

@sec:model describes the model, the estimator and the structure of the code. @sec:validation validates European prices against the Black–Scholes formula. @sec:exotics prices Asian and barrier options, whose payoffs depend on the whole path, and checks them against independent references. @sec:greeks estimates Greeks by finite differences. @sec:limitations states what is not new and the limitations of the implementation, and @app:reproduce explains how to reproduce the results. Every number and figure in this note is produced by a single script from fixed random seeds.

= Model and estimator <sec:model>

== Risk-neutral dynamics

Under the risk-neutral measure $QQ$ the price of the underlying follows a geometric Brownian motion,
$ d S_t = r S_t thin d t + sigma S_t thin d W_t, $
with constant risk-free rate $r$ and volatility $sigma$. Its solution gives the exact update over a step of length $tau$:
$ S_(t + tau) = S_t exp[(r - 1/2 sigma^2) tau + sigma sqrt(tau) thin Z], quad Z tilde cal(N)(0, 1). $
The term $-1/2 sigma^2$ is the Itô correction that makes $EE^QQ [S_T] = S_0 e^(r T)$. Paths are simulated on the grid $t_i = i T\/n$, $i = 0, dots, n$, with independent normal draws at each step. The scheme has no discretization error at the grid points, so a European payoff, which depends only on $S_T$, needs a single step. For the path-dependent contracts of @sec:exotics the grid is part of the contract: $n$ is the number of monitoring dates.

Unless stated otherwise, $S_0 = #R.parameters.S0$, $K = #R.parameters.K$, $r = #R.parameters.r$, $sigma = #R.parameters.sigma$ and $T = #R.parameters.T$ year.

== Estimator and standard error

With $N$ simulated paths and discounted payoffs $X_i = e^(-r T) thin "payoff"_i$, the price estimate and its standard error are
$ hat(V) = 1/N sum_(i=1)^N X_i, quad "SE" = s / sqrt(N), $
where $s$ is the sample standard deviation of the $X_i$. By the central limit theorem, $hat(V) plus.minus 1.96 thin "SE"$ is an approximate 95% confidence interval. Halving the standard error requires four times as many paths.

== Structure of the code

The package separates the three questions that a pricer must answer:
- the *model* (`GBM`) describes how the underlying moves, and returns a matrix of simulated paths;
- an *instrument* (`EuropeanCall`, `AsianOption`, `BarrierOption`, …) describes what the contract pays on each path;
- the *engine* (`price_monte_carlo`) combines the two and returns the estimate with its standard error and confidence interval.

The engine never inspects the type of contract, so the exotic options of @sec:exotics were added as new instrument classes without changing it. Separate modules provide the Black–Scholes formulas, the validation routines and the Greeks. A complete pricing call reads:

```
model = GBM(S0=100, r=0.05, sigma=0.20)
option = BarrierOption(K=100, T=1, barrier=130,
                       kind="call", direction="up", knock="out")
result = price_monte_carlo(model, option,
                           n_paths=100_000, n_steps=252, seed=42)
```

= Validation against Black–Scholes <sec:validation>

For European options the Black–Scholes formula [1] gives the exact price under the model of @sec:model:
$ C = S_0 N(d_1) - K e^(-r T) N(d_2), quad P = K e^(-r T) N(-d_2) - S_0 N(-d_1), $
$ d_2 = (ln(S_0 \/ K) + (r - 1/2 sigma^2) T) / (sigma sqrt(T)), quad d_1 = d_2 + sigma sqrt(T), $
where $N$ is the standard normal distribution function. The implementation of the formulas was first checked without Monte Carlo: put–call parity, $C - P = S_0 - K e^(-r T)$, holds on #R.parity.cases random inputs with a largest discrepancy of #R.parity.mantissa × 10#super[#R.parity.exponent].

*Base case.* With $N = #R.base.N$ paths the Monte Carlo prices are #R.base.call.mc ± #R.base.call.se for the call and #R.base.put.mc ± #R.base.put.se for the put (estimate ± SE), against Black–Scholes prices of #R.base.call.bs and #R.base.put.bs;; the z-scores are #R.base.call.z and #R.base.put.z.

*Twelve scenarios.* A single at-the-money test is weak: with $S_0 = K$ some errors are invisible, for instance exchanging $S_0$ and $K$ in the call formula leaves its value unchanged. @tab:scenarios repeats the comparison for in- and out-of-the-money strikes, high volatility, and short and long maturities. The largest deviation is #R.scenarios.max_abs_z standard errors, and #R.scenarios.outside of the #R.scenarios.count Black–Scholes prices lies outside the 95% confidence interval: the call with $K = 80$, with $z = $ #R.scenarios.rows.at(2).z.

#figure(
  table(
    columns: 8,
    align: (right, right, right, left, right, right, right, right),
    toprule,
    table.header([$K$], [$T$], [$sigma$], [Option], [Black–Scholes], [Monte Carlo], [SE], [$z$]),
    midrule,
    ..R.scenarios.rows.map(row => (row.K, row.T, row.sigma, row.type, row.bs, row.mc, row.se, row.z)).flatten(),
    bottomrule,
  ),
  caption: [European prices against Black–Scholes, with $S_0 = #R.parameters.S0$, $r = #R.parameters.r$ and $N = #R.base.N$ paths per scenario. Each scenario uses its own seed, and its call and put share the same paths.],
) <tab:scenarios>

This is not evidence of an error. Even with a correct engine, among twelve tests at the 95% level at least one falls outside with probability close to one half ($1 - 0.95^12 approx 0.46$ for independent tests). The appropriate check is to repeat that scenario with independent seeds. Over #R.repeat.runs runs of $N = #R.repeat.N$ paths each, the z-scores have mean #R.repeat.mean_z (standard error #R.repeat.mean_z_se), standard deviation #R.repeat.sd_z, and #R.repeat.coverage of them lie within ±1.96, as expected from a standard normal variable. A systematic error would move the mean away from zero.

*Convergence.* @fig:convergence shows estimates for #R.convergence.points values of $N$ between $10^2$ and $10^6$, each from an independent simulation. The band is the region $V plus.minus 1.96 thin s \/ sqrt(N)$ in which about 95% of the estimates should fall if the engine is correct; it narrows as $1\/sqrt(N)$, and it contains #R.convergence.call of the #R.convergence.points call estimates and #R.convergence.put of the put estimates.

#figure(
  image("figures/convergence.svg", width: 100%),
  caption: [Monte Carlo estimates of the European call (a) and put (b) for #R.convergence.points values of $N$, each from an independent simulation, against the Black–Scholes price. The shaded band, $plus.minus 1.96 thin s \/ sqrt(N)$ around the exact price, is where 95% of the estimates are expected to fall.],
) <fig:convergence>

= Path-dependent options <sec:exotics>

== Contracts

*Asian option.* The payoff depends on the arithmetic average of the prices observed at the monitoring dates, $A = 1/n sum_(i=1)^n S_(t_i)$, and the call pays $max(A - K, 0)$. A sum of lognormal variables is not lognormal, and no closed-form price is available.

*Barrier options.* A knock-out option becomes worthless if the underlying reaches a barrier $B$ during its life; a knock-in option comes into existence only if it does. Otherwise they pay as the corresponding European option. Here the barrier is monitored on the simulation dates, as in contracts that refer to daily closing prices. On every path exactly one of the knock-in and knock-out options is alive, so their prices add up to the European price (in–out parity).

A path matrix with a single step contains only $S_0$ and $S_T$, and a path-dependent payoff computed from it would be silently wrong: the average would reduce to $S_T$, and crossings of the barrier during the life would be missed. The Asian and barrier classes therefore reject simulations with fewer than two steps.

== Prices

@tab:exotics lists prices for daily monitoring ($n = #R.exotics.steps$) with $N = #R.exotics.N$ paths. Knock-in and knock-out prices computed from the same paths add up exactly to the European prices (the difference is #R.exotics.parity_gap in floating point), and the European call simulated on the #R.exotics.steps\-step grid remains consistent with Black–Scholes ($z = $ #R.exotics.european_252_z). The Asian call costs #R.exotics.asian_ratio of the European call.

#figure(
  table(
    columns: 3,
    align: (left, right, right),
    toprule,
    table.header([Option], [Monte Carlo], [SE]),
    midrule,
    ..R.exotics.rows.map(row => (row.name, row.mc, row.se)).flatten(),
    bottomrule,
  ),
  caption: [Prices with daily monitoring ($n = #R.exotics.steps$), $K = #R.parameters.K$, up barrier $B = #R.parameters.B_up$ for the calls and down barrier $B = #R.parameters.B_down$ for the puts; $N = #R.exotics.N$ paths with the same seed for all contracts.],
) <tab:exotics>

*Monitoring frequency.* For these contracts the price depends on how often the underlying is observed (@fig:monitoring). From semi-annual to daily monitoring the Asian call falls from #R.monitoring.at("Asian call").first() to #R.monitoring.at("Asian call").last(), because the average includes more early prices, which have had less time to disperse. The up-and-out call falls from #R.monitoring.at("Up-and-out call").first() to #R.monitoring.at("Up-and-out call").last(), because more monitoring dates detect more crossings of the barrier. The European price does not depend on $n$.

#figure(
  image("figures/monitoring.svg", width: 72%),
  caption: [Monte Carlo prices against the number $n$ of monitoring dates per year, from semi-annual ($n = 2$) to daily ($n = 252$), with $N = #R.exotics.N$ paths per point and error bars for the 95% confidence interval.],
) <fig:monitoring>

*Why the Asian option is cheaper.* @fig:asian compares the distribution of $S_T$ with that of $A$. Both exceed the strike with similar probability (#R.asian.itm_ST and #R.asian.itm_A), but $A$ is far less dispersed: its standard deviation is #R.asian.sd_A against #R.asian.sd_ST. The standard deviation of $ln A$ is #R.asian.logvol_A, close to $sigma sqrt(T \/ 3) = $ #R.asian.sigma_sqrt3, the value for the logarithm of a continuously sampled geometric average.

#figure(
  image("figures/asian_distribution.svg", width: 72%),
  caption: [Distribution of the terminal price $S_T$, on which the European call pays, and of the arithmetic average $A$ of #R.exotics.steps daily prices, on which the Asian call pays; $N = #R.exotics.N$ paths.],
) <fig:asian>

*Path dependence.* @fig:barrier shows two paths that end at the same price, #R.barrier.S_T. The path that never touches the barrier pays #R.barrier.alive_payoff;; the other touches it at $t = $ #R.barrier.touch_time and pays nothing. Across all paths, #R.barrier.hit_share touch the barrier, and among those that end between $K$ and $B$, where the European call pays, #R.barrier.hit_share_between have been knocked out.

#figure(
  image("figures/barrier.svg", width: 100%),
  caption: [Up-and-out call with $K = #R.parameters.K$ and $B = #R.parameters.B_up$. (a) Two paths with the same terminal price: only the one that never touches the barrier pays. (b) Payoff against $S_T$ for #R.barrier.sample paths: between $K$ and $B$ the same terminal price can give a positive or a zero payoff.],
) <fig:barrier>

== Independent reference checks <sec:reference-checks>

The arithmetic Asian option has no closed form, but a call on the _geometric_ average of $n$ equally spaced observations does, because the logarithm of the geometric average is normal [6]. It shares the simulation grid and the averaging step with the arithmetic contract, so it tests both. For the up-and-out call, a closed-form price exists under continuous monitoring [2, 4]. Broadie, Glasserman and Kou [5] showed that monitoring on $n$ dates is well approximated by the continuous formula with the barrier shifted to $B e^(beta sigma sqrt(T \/ n))$, where $beta approx 0.5826$; being asymptotic, the correction is expected to agree up to a small remainder.

@tab:references compares both references with estimates pooled over #R.reference_checks.runs independent simulations of #R.exotics.N paths each (#R.reference_checks.N in total). Both agree within their standard errors, with $z = $ #R.reference_checks.geometric.z and $z = $ #R.reference_checks.up_out.z. The continuous-monitoring price without correction, #R.reference_checks.up_out.continuous, would be clearly rejected, in line with @fig:monitoring. As a further consistency check, the arithmetic Asian price, #R.reference_checks.arithmetic.mc ± #R.reference_checks.arithmetic.se, exceeds the geometric one, as the inequality between arithmetic and geometric means requires.

#figure(
  table(
    columns: 6,
    align: (left, left, right, right, right, right),
    toprule,
    table.header([Option], [Reference], [Reference price], [Monte Carlo], [SE], [$z$]),
    midrule,
    [Geometric Asian call], [Exact, discrete monitoring [6]],
    R.reference_checks.geometric.ref, R.reference_checks.geometric.mc, R.reference_checks.geometric.se, R.reference_checks.geometric.z,
    [Up-and-out call], [Continuous, with correction [4, 5]],
    R.reference_checks.up_out.ref, R.reference_checks.up_out.mc, R.reference_checks.up_out.se, R.reference_checks.up_out.z,
    bottomrule,
  ),
  caption: [Path-dependent prices against closed-form references, with daily monitoring ($n = #R.exotics.steps$) and $N = #R.reference_checks.N$ paths from #R.reference_checks.runs independent simulations.],
) <tab:references>

= Greeks <sec:greeks>

== Finite differences with common random numbers

Greeks measure how the price responds to the model parameters. Without a formula to differentiate, they are approximated by central finite differences,
$ Delta approx (V(S_0 + h) - V(S_0 - h)) / (2h), quad Gamma approx (V(S_0 + h) - 2V(S_0) + V(S_0 - h)) / h^2, $
$ cal(V) approx (V(sigma + k) - V(sigma - k)) / (2k), $
with $h = 0.01 thin S_0$ and $k = 0.01$. The difficulty is noise: $V(S_0 + h)$ and $V(S_0 - h)$ are estimates of two nearly equal numbers, and dividing their statistical errors by $2h$, or by $h^2$, amplifies them. The remedy is to simulate all bumped prices with the same normal draws, known as common random numbers [3, Ch. 7]. Since $"Var"(X - Y) = "Var"(X) + "Var"(Y) - 2 "Cov"(X, Y)$ and the covariance is then close to its maximum, most of the noise cancels in the difference. The differences are taken path by path, which yields a standard error for each Greek.

== European options

For the European call the Greeks are known in closed form: $Delta = N(d_1)$, $Gamma = phi(d_1) \/ (S_0 sigma sqrt(T))$ and $cal(V) = S_0 phi(d_1) sqrt(T)$, where $phi$ is the standard normal density. @tab:greeks-european compares them with the finite-difference estimates; the largest deviation is #R.greeks_european.max_abs_z standard errors. Repeating the computation with a different seed for each bumped simulation leaves the estimates unbiased, but multiplies the standard errors by the factors in the last column. Matching the precision of common random numbers with independent seeds would require #R.greeks_european.rows.at(0).paths_factor, #R.greeks_european.rows.at(1).paths_factor and #R.greeks_european.rows.at(2).paths_factor times as many paths for delta, gamma and vega respectively.

#figure(
  table(
    columns: 7,
    align: (left, right, right, right, right, right, right),
    toprule,
    table.header([Greek], [Monte Carlo], [SE], [Black–Scholes], [$z$], [SE, independent seeds], [Ratio]),
    midrule,
    ..R.greeks_european.rows.map(row => (row.name, row.mc, row.se, row.bs, row.z, row.se_indep, row.ratio + "×")).flatten(),
    bottomrule,
  ),
  caption: [Greeks of the European call by central finite differences with common random numbers ($N = #R.greeks_european.N$ paths), against the Black–Scholes values. The last two columns give the standard error obtained with independent seeds instead, and its ratio to the standard error with common random numbers.],
) <tab:greeks-european>

== Path-dependent options <sec:greeks-exotic>

@tab:greeks-exotic reports the Greeks of the Asian and up-and-out calls under daily monitoring. The Asian call has lower delta and vega than the European call, but higher gamma. Averaging lowers the effective volatility, which reduces vega, and concentrates the distribution of the payoff variable around the strike, which raises gamma, as it would for a European option with lower volatility. The up-and-out call has negative vega: higher volatility makes a knock-out more likely, and this outweighs the usual gain in option value. Its delta is close to zero, because a rise in the underlying moves the option into the money and towards the barrier at the same time. The reference values in the last row differentiate the corrected closed-form price of @sec:reference-checks numerically.

#let pm(g) = [#g.v ± #g.se]
#figure(
  table(
    columns: 4,
    align: (left, right, right, right),
    toprule,
    table.header([Option], [Delta], [Gamma], [Vega]),
    midrule,
    ..R.greeks_exotic.rows.map(row => (row.name, pm(row.delta), pm(row.gamma), pm(row.vega))).flatten(),
    midrule,
    [Up-and-out call, reference], R.greeks_exotic.up_out_reference.delta, R.greeks_exotic.up_out_reference.gamma, R.greeks_exotic.up_out_reference.vega,
    bottomrule,
  ),
  caption: [Greeks (estimate ± SE) with daily monitoring, $h = 0.01 thin S_0$, $k = 0.01$ and $N = #R.greeks_european.N$ paths. The reference for the up-and-out call uses the continuous formula with the Broadie–Glasserman–Kou correction.],
) <tab:greeks-exotic>

The gamma of the up-and-out call shows the limits of finite differences. Its payoff jumps from as much as $B - K = 30$ to zero when the barrier is touched, so a bump of $S_0$ changes the payoff only on the few paths whose maximum lies close to the barrier, but on those paths by a large amount. With $h = 0.01 thin S_0$ the estimate is #R.greeks_exotic.bumps.at(0).gamma ± #R.greeks_exotic.bumps.at(0).gamma_se, with a standard error larger than the value itself; with $h = 0.05 thin S_0$ it is #R.greeks_exotic.bumps.at(2).gamma ± #R.greeks_exotic.bumps.at(2).gamma_se, close to the reference #R.greeks_exotic.up_out_reference.gamma (@tab:bumps). A larger bump reduces the variance at the cost of a larger approximation bias.

#figure(
  table(
    columns: 5,
    align: (left, right, right, right, right),
    toprule,
    table.header([Bump $h \/ S_0$], [Delta], [SE], [Gamma], [SE]),
    midrule,
    ..R.greeks_exotic.bumps.map(row => (row.bump, row.delta, row.delta_se, row.gamma, row.gamma_se)).flatten(),
    midrule,
    [Reference], R.greeks_exotic.up_out_reference.delta, [], R.greeks_exotic.up_out_reference.gamma, [],
    bottomrule,
  ),
  caption: [Delta and gamma of the up-and-out call for three bump sizes, with the same paths ($N = #R.greeks_european.N$, daily monitoring).],
) <tab:bumps>

= What is not new, and limitations <sec:limitations>

*Not new.* Everything implemented here is textbook material: Monte Carlo pricing and finite-difference Greeks with common random numbers [3], the Black–Scholes formula [1], closed-form barrier prices [2, 4], the continuity correction for discrete monitoring [5] and the price of the geometric Asian option [6].

*What this work consists of.* An implementation in which models, contracts and the pricing engine are independent, so that new contracts leave the engine unchanged; and a validation protocol in which every estimate carries a standard error, agreement is judged by z-scores, an apparent failure is re-examined with independent seeds rather than hidden, and path-dependent prices are checked against independent references. All results can be reproduced with one script (@app:reproduce).

*Limitations.* The implementation has four main limitations.
- The model has constant volatility and interest rate and no dividends, and it is not calibrated to market prices; volatility smiles and term structures are outside its scope.
- Paths are stored in full, so memory grows as $N n$: #R.exotics.N paths of #(R.exotics.steps + 1) prices take about 200~MB per array.
- Finite-difference Greeks of discontinuous payoffs are noisy (@sec:greeks-exotic); pathwise or likelihood-ratio estimators [3, Ch. 7] would be more suitable.
- Apart from common random numbers, no variance reduction is used; antithetic sampling and control variates [3, Ch. 4] are the natural next step.

*Provenance.* The code and this note were developed in working sessions with an AI language model (Claude Opus 5, Anthropic) under the author's direction. All numbers and figures are produced by the accompanying script from fixed seeds, and were checked as described in the preceding sections.

#heading(numbering: none)[References]

#set par(first-line-indent: 0em)
#grid(
  columns: (auto, 1fr),
  column-gutter: 0.7em,
  row-gutter: 0.75em,
  [[1]], [F. Black and M. Scholes, The pricing of options and corporate liabilities, _Journal of Political Economy_ 81(3), 637–654, 1973.],
  [[2]], [R. C. Merton, Theory of rational option pricing, _Bell Journal of Economics and Management Science_ 4(1), 141–183, 1973.],
  [[3]], [P. Glasserman, _Monte Carlo Methods in Financial Engineering_, Springer, 2003.],
  [[4]], [E. Reiner and M. Rubinstein, Breaking down the barriers, _Risk_ 4(8), 28–35, 1991.],
  [[5]], [M. Broadie, P. Glasserman and S. Kou, A continuity correction for discrete barrier options, _Mathematical Finance_ 7(4), 325–349, 1997.],
  [[6]], [A. G. Z. Kemna and A. C. F. Vorst, A pricing method for options based on average asset values, _Journal of Banking & Finance_ 14(1), 113–129, 1990.],
)

// ---------------------------------------------------------------------------
// Appendix
// ---------------------------------------------------------------------------

#counter(heading).update(0)
#set heading(numbering: "A.1", supplement: [Appendix])
#set par(first-line-indent: 1.2em)

= Reproducing the results <app:reproduce>

#if repo != none [
  The code is available at #link(repo)[#raw(repo)].
] else [
  The code is available from the author on request.
]
The project contains the package `option_pricer` (models, instruments, pricing engine, Black–Scholes formulas, validation routines, Greeks and plotting style), three notebooks that present the same material step by step, and the folder `report`, which holds this note, the script that produces its numbers and figures, and the font used in both. From the root of the project:

```
python3 -m pip install -r requirements.txt
python3 report/build_assets.py
typst compile --root . report/report.typ report/option_pricer_report.pdf
```

The script writes the figures to `report/figures` and every number quoted in this note to `report/results.json`, which the document reads when it is compiled; no number in the text is typed by hand. It runs in about 20 seconds on a laptop. The results above were obtained with Python #R.environment.python, NumPy #R.environment.numpy, SciPy #R.environment.scipy, Matplotlib #R.environment.matplotlib and Typst 0.15.1.

All random numbers come from NumPy's default generator with fixed seeds: #R.parameters.seed for the main results, $#R.parameters.seed + i$ for scenario $i$ of @tab:scenarios, $1000 + j$ for the repeated runs of @sec:validation and $2000 + r$ for the reference checks of @sec:reference-checks. Running the script again reproduces every number exactly.
